http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  user:
      host: localhost
      paths: ['/user', '/user/*']
  order:
    host: localhost
    paths: ['/order', '/order/*']

serviceEndpoints:
  userService:
    url: 'http://localhost:4000'
  orderService:
    url: 'http://localhost:4001'

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  userPipeline:
    apiEndpoints:
      - user
    policies:
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true
  orderPipeline:
    apiEndpoints:
      - order
    policies:
      - proxy:
          - action:
              serviceEndpoint: orderService
              changeOrigin: true